//
//Copyright The containerd Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: proto/nerdbox/types/sandbox.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CRIPodConfig is a hand-maintained, wire-compatible *subset* of
// k8s.io/cri-api's runtime.v1.PodSandboxConfig (the type containerd's CRI
// plugin marshals into CreateSandboxRequest.Options — see
// internal/shim/task/podconfig.go), covering only the fields the shim
// actually reads: pod hostname, DNS config, and Linux sysctls.
//
// This intentionally does NOT import k8s.io/cri-api: that package pulls in
// gRPC unconditionally (its generated *_grpc.pb.go carries no build tag),
// which defeats the shim's "no_grpc" build tag for the sake of decoding
// three scalar-ish fields out of an otherwise-unused message. Protobuf's
// wire format tolerates this: an unrecognized field number is simply
// skipped on decode, so a real CRI PodSandboxConfig — which carries many
// more fields than these — decodes cleanly into this subset, silently
// dropping everything this shim doesn't need.
//
// Field numbers below (and every message's nesting level) are copied
// verbatim from the upstream message (CRI v1, github.com/kubernetes/cri-api,
// pkg/apis/runtime/v1/api.proto) and MUST continue to match it exactly:
// this only decodes correctly because the wire bytes line up field-for-field
// with upstream at every level, not just the top one. CRI v1 is a frozen,
// GA, append-only-evolution API (see kubernetes/cri-api's own compatibility
// policy), so existing field numbers are not expected to ever be reused or
// renumbered. Field numbers NOT listed here (e.g. PodSandboxConfig's own
// 1, 3, 5, 6, 7, 9, 10) are other upstream fields this shim has no use for;
// they are simply omitted rather than declared, and are skipped like any
// other unrecognized field on decode.
//
// Deliberately named and packaged differently than upstream's
// runtime.v1.PodSandboxConfig, rather than reusing that exact
// fully-qualified proto name: registering a second, different message
// under upstream's own name would panic at process init if this binary
// ever also imported the real k8s.io/cri-api (protobuf-go's global type
// registry rejects duplicate registrations for the same full name).
type CRIPodConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Hostname of the sandbox (upstream field 2).
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// DNS config for the sandbox (upstream field 4).
	DnsConfig *CRIDNSConfig `protobuf:"bytes,4,opt,name=dns_config,json=dnsConfig,proto3" json:"dns_config,omitempty"`
	// Linux-specific pod sandbox config (upstream field 8).
	Linux *CRILinuxPodSandboxConfig `protobuf:"bytes,8,opt,name=linux,proto3" json:"linux,omitempty"`
}

func (x *CRIPodConfig) Reset() {
	*x = CRIPodConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_types_sandbox_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CRIPodConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRIPodConfig) ProtoMessage() {}

func (x *CRIPodConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_types_sandbox_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRIPodConfig.ProtoReflect.Descriptor instead.
func (*CRIPodConfig) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_types_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *CRIPodConfig) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *CRIPodConfig) GetDnsConfig() *CRIDNSConfig {
	if x != nil {
		return x.DnsConfig
	}
	return nil
}

func (x *CRIPodConfig) GetLinux() *CRILinuxPodSandboxConfig {
	if x != nil {
		return x.Linux
	}
	return nil
}

// CRIDNSConfig is a wire-compatible subset of runtime.v1.DNSConfig,
// covering every field it has today (unlike CRIPodConfig, this one just
// happens to be complete). See CRIPodConfig's doc comment for why this is
// a hand-maintained copy rather than an import.
type CRIDNSConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of DNS servers of the cluster (upstream field 1).
	Servers []string `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	// List of DNS search domains of the cluster (upstream field 2).
	Searches []string `protobuf:"bytes,2,rep,name=searches,proto3" json:"searches,omitempty"`
	// List of DNS options; see resolv.conf(5) (upstream field 3).
	Options []string `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *CRIDNSConfig) Reset() {
	*x = CRIDNSConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_types_sandbox_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CRIDNSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRIDNSConfig) ProtoMessage() {}

func (x *CRIDNSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_types_sandbox_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRIDNSConfig.ProtoReflect.Descriptor instead.
func (*CRIDNSConfig) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_types_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *CRIDNSConfig) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *CRIDNSConfig) GetSearches() []string {
	if x != nil {
		return x.Searches
	}
	return nil
}

func (x *CRIDNSConfig) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// CRILinuxPodSandboxConfig is a wire-compatible subset of
// runtime.v1.LinuxPodSandboxConfig, covering only the field this shim
// reads (pod-level sysctls). See CRIPodConfig's doc comment for why this
// is a hand-maintained copy rather than an import.
type CRILinuxPodSandboxConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sysctls to apply within the pod's containers (upstream field 3).
	// Fields NOT listed here (upstream 1, 2, 4, 5) are omitted; see
	// CRIPodConfig's doc comment.
	Sysctls map[string]string `protobuf:"bytes,3,rep,name=sysctls,proto3" json:"sysctls,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CRILinuxPodSandboxConfig) Reset() {
	*x = CRILinuxPodSandboxConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_types_sandbox_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CRILinuxPodSandboxConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRILinuxPodSandboxConfig) ProtoMessage() {}

func (x *CRILinuxPodSandboxConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_types_sandbox_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRILinuxPodSandboxConfig.ProtoReflect.Descriptor instead.
func (*CRILinuxPodSandboxConfig) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_types_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *CRILinuxPodSandboxConfig) GetSysctls() map[string]string {
	if x != nil {
		return x.Sysctls
	}
	return nil
}

var File_proto_nerdbox_types_sandbox_proto protoreflect.FileDescriptor

var file_proto_nerdbox_types_sandbox_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x72, 0x64, 0x62, 0x6f, 0x78, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6e, 0x65, 0x72, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x22, 0xa5, 0x01, 0x0a, 0x0c, 0x43, 0x52, 0x49, 0x50, 0x6f, 0x64, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x3a, 0x0a, 0x0a, 0x64, 0x6e, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e, 0x65, 0x72, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x43, 0x52, 0x49, 0x44, 0x4e, 0x53, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x09, 0x64, 0x6e, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x3d, 0x0a, 0x05, 0x6c,
	0x69, 0x6e, 0x75, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6e, 0x65, 0x72,
	0x64, 0x62, 0x6f, 0x78, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x52, 0x49, 0x4c, 0x69,
	0x6e, 0x75, 0x78, 0x50, 0x6f, 0x64, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x75, 0x78, 0x22, 0x5e, 0x0a, 0x0c, 0x43, 0x52,
	0x49, 0x44, 0x4e, 0x53, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x65, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xa6, 0x01, 0x0a, 0x18, 0x43,
	0x52, 0x49, 0x4c, 0x69, 0x6e, 0x75, 0x78, 0x50, 0x6f, 0x64, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x4e, 0x0a, 0x07, 0x73, 0x79, 0x73, 0x63, 0x74,
	0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x6e, 0x65, 0x72, 0x64, 0x62,
	0x6f, 0x78, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x52, 0x49, 0x4c, 0x69, 0x6e, 0x75,
	0x78, 0x50, 0x6f, 0x64, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x53, 0x79, 0x73, 0x63, 0x74, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07,
	0x73, 0x79, 0x73, 0x63, 0x74, 0x6c, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x53, 0x79, 0x73, 0x63, 0x74,
	0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2f, 0x6e, 0x65, 0x72,
	0x64, 0x62, 0x6f, 0x78, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x3b, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_nerdbox_types_sandbox_proto_rawDescOnce sync.Once
	file_proto_nerdbox_types_sandbox_proto_rawDescData = file_proto_nerdbox_types_sandbox_proto_rawDesc
)

func file_proto_nerdbox_types_sandbox_proto_rawDescGZIP() []byte {
	file_proto_nerdbox_types_sandbox_proto_rawDescOnce.Do(func() {
		file_proto_nerdbox_types_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_nerdbox_types_sandbox_proto_rawDescData)
	})
	return file_proto_nerdbox_types_sandbox_proto_rawDescData
}

var file_proto_nerdbox_types_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_nerdbox_types_sandbox_proto_goTypes = []interface{}{
	(*CRIPodConfig)(nil),             // 0: nerdbox.types.CRIPodConfig
	(*CRIDNSConfig)(nil),             // 1: nerdbox.types.CRIDNSConfig
	(*CRILinuxPodSandboxConfig)(nil), // 2: nerdbox.types.CRILinuxPodSandboxConfig
	nil,                              // 3: nerdbox.types.CRILinuxPodSandboxConfig.SysctlsEntry
}
var file_proto_nerdbox_types_sandbox_proto_depIdxs = []int32{
	1, // 0: nerdbox.types.CRIPodConfig.dns_config:type_name -> nerdbox.types.CRIDNSConfig
	2, // 1: nerdbox.types.CRIPodConfig.linux:type_name -> nerdbox.types.CRILinuxPodSandboxConfig
	3, // 2: nerdbox.types.CRILinuxPodSandboxConfig.sysctls:type_name -> nerdbox.types.CRILinuxPodSandboxConfig.SysctlsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_nerdbox_types_sandbox_proto_init() }
func file_proto_nerdbox_types_sandbox_proto_init() {
	if File_proto_nerdbox_types_sandbox_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_nerdbox_types_sandbox_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CRIPodConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_types_sandbox_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CRIDNSConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_types_sandbox_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CRILinuxPodSandboxConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_nerdbox_types_sandbox_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_nerdbox_types_sandbox_proto_goTypes,
		DependencyIndexes: file_proto_nerdbox_types_sandbox_proto_depIdxs,
		MessageInfos:      file_proto_nerdbox_types_sandbox_proto_msgTypes,
	}.Build()
	File_proto_nerdbox_types_sandbox_proto = out.File
	file_proto_nerdbox_types_sandbox_proto_rawDesc = nil
	file_proto_nerdbox_types_sandbox_proto_goTypes = nil
	file_proto_nerdbox_types_sandbox_proto_depIdxs = nil
}
