// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: proto/nerdbox/services/podns/v1/podns.proto
package podns

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type TTRPCPodNamespacesService interface {
	EnsureNamespaces(context.Context, *EnsureNamespacesRequest) (*EnsureNamespacesResponse, error)
}

func RegisterTTRPCPodNamespacesService(srv *ttrpc.Server, svc TTRPCPodNamespacesService) {
	srv.RegisterService("containerd.vminitd.services.podns.v1.PodNamespaces", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"EnsureNamespaces": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req EnsureNamespacesRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.EnsureNamespaces(ctx, &req)
			},
		},
	})
}

type ttrpcpodnamespacesClient struct {
	client *ttrpc.Client
}

func NewTTRPCPodNamespacesClient(client *ttrpc.Client) TTRPCPodNamespacesService {
	return &ttrpcpodnamespacesClient{
		client: client,
	}
}

func (c *ttrpcpodnamespacesClient) EnsureNamespaces(ctx context.Context, req *EnsureNamespacesRequest) (*EnsureNamespacesResponse, error) {
	var resp EnsureNamespacesResponse
	if err := c.client.Call(ctx, "containerd.vminitd.services.podns.v1.PodNamespaces", "EnsureNamespaces", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
