// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: proto/nerdbox/services/namespaces/v1/namespaces.proto
package namespaces

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type TTRPCNamespaceManagerService interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterTTRPCNamespaceManagerService(srv *ttrpc.Server, svc TTRPCNamespaceManagerService) {
	srv.RegisterService("containerd.vminitd.services.namespaces.v1.NamespaceManager", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"Create": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req CreateRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Create(ctx, &req)
			},
			"Delete": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req DeleteRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Delete(ctx, &req)
			},
		},
	})
}

type ttrpcnamespacemanagerClient struct {
	client *ttrpc.Client
}

func NewTTRPCNamespaceManagerClient(client *ttrpc.Client) TTRPCNamespaceManagerService {
	return &ttrpcnamespacemanagerClient{
		client: client,
	}
}

func (c *ttrpcnamespacemanagerClient) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	var resp CreateResponse
	if err := c.client.Call(ctx, "containerd.vminitd.services.namespaces.v1.NamespaceManager", "Create", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcnamespacemanagerClient) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	var resp DeleteResponse
	if err := c.client.Call(ctx, "containerd.vminitd.services.namespaces.v1.NamespaceManager", "Delete", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
