// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: proto/nerdbox/services/mount/v1/mount.proto
package mount

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type TTRPCMountService interface {
	MountAll(context.Context, *MountAllRequest) (*MountAllResponse, error)
	Unmount(context.Context, *UnmountRequest) (*UnmountResponse, error)
	UnmountAll(context.Context, *UnmountAllRequest) (*UnmountAllResponse, error)
	MountInContainer(context.Context, *MountInContainerRequest) (*MountInContainerResponse, error)
	UnmountInContainer(context.Context, *UnmountInContainerRequest) (*UnmountInContainerResponse, error)
}

func RegisterTTRPCMountService(srv *ttrpc.Server, svc TTRPCMountService) {
	srv.RegisterService("containerd.vminitd.services.mount.v1.Mount", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"MountAll": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req MountAllRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.MountAll(ctx, &req)
			},
			"Unmount": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req UnmountRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Unmount(ctx, &req)
			},
			"UnmountAll": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req UnmountAllRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.UnmountAll(ctx, &req)
			},
			"MountInContainer": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req MountInContainerRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.MountInContainer(ctx, &req)
			},
			"UnmountInContainer": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req UnmountInContainerRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.UnmountInContainer(ctx, &req)
			},
		},
	})
}

type ttrpcmountClient struct {
	client *ttrpc.Client
}

func NewTTRPCMountClient(client *ttrpc.Client) TTRPCMountService {
	return &ttrpcmountClient{
		client: client,
	}
}

func (c *ttrpcmountClient) MountAll(ctx context.Context, req *MountAllRequest) (*MountAllResponse, error) {
	var resp MountAllResponse
	if err := c.client.Call(ctx, "containerd.vminitd.services.mount.v1.Mount", "MountAll", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcmountClient) Unmount(ctx context.Context, req *UnmountRequest) (*UnmountResponse, error) {
	var resp UnmountResponse
	if err := c.client.Call(ctx, "containerd.vminitd.services.mount.v1.Mount", "Unmount", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcmountClient) UnmountAll(ctx context.Context, req *UnmountAllRequest) (*UnmountAllResponse, error) {
	var resp UnmountAllResponse
	if err := c.client.Call(ctx, "containerd.vminitd.services.mount.v1.Mount", "UnmountAll", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcmountClient) MountInContainer(ctx context.Context, req *MountInContainerRequest) (*MountInContainerResponse, error) {
	var resp MountInContainerResponse
	if err := c.client.Call(ctx, "containerd.vminitd.services.mount.v1.Mount", "MountInContainer", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcmountClient) UnmountInContainer(ctx context.Context, req *UnmountInContainerRequest) (*UnmountInContainerResponse, error) {
	var resp UnmountInContainerResponse
	if err := c.client.Call(ctx, "containerd.vminitd.services.mount.v1.Mount", "UnmountInContainer", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
