//
//Copyright The containerd Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: proto/nerdbox/services/mount/v1/mount.proto

package mount

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MountSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source  string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // in-VM path or virtiofs tag
	Target  string   `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"` // in-VM path
	Options []string `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *MountSpec) Reset() {
	*x = MountSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MountSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountSpec) ProtoMessage() {}

func (x *MountSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountSpec.ProtoReflect.Descriptor instead.
func (*MountSpec) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_mount_v1_mount_proto_rawDescGZIP(), []int{0}
}

func (x *MountSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MountSpec) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MountSpec) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MountSpec) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type MountAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mounts []*MountSpec `protobuf:"bytes,1,rep,name=mounts,proto3" json:"mounts,omitempty"`
}

func (x *MountAllRequest) Reset() {
	*x = MountAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MountAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountAllRequest) ProtoMessage() {}

func (x *MountAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountAllRequest.ProtoReflect.Descriptor instead.
func (*MountAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_mount_v1_mount_proto_rawDescGZIP(), []int{1}
}

func (x *MountAllRequest) GetMounts() []*MountSpec {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type MountAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MountAllResponse) Reset() {
	*x = MountAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MountAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountAllResponse) ProtoMessage() {}

func (x *MountAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountAllResponse.ProtoReflect.Descriptor instead.
func (*MountAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_mount_v1_mount_proto_rawDescGZIP(), []int{2}
}

type UnmountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"` // in-VM path
}

func (x *UnmountRequest) Reset() {
	*x = UnmountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountRequest) ProtoMessage() {}

func (x *UnmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountRequest.ProtoReflect.Descriptor instead.
func (*UnmountRequest) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_mount_v1_mount_proto_rawDescGZIP(), []int{3}
}

func (x *UnmountRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type UnmountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnmountResponse) Reset() {
	*x = UnmountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountResponse) ProtoMessage() {}

func (x *UnmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountResponse.ProtoReflect.Descriptor instead.
func (*UnmountResponse) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_mount_v1_mount_proto_rawDescGZIP(), []int{4}
}

type UnmountAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnmountAllRequest) Reset() {
	*x = UnmountAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmountAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountAllRequest) ProtoMessage() {}

func (x *UnmountAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountAllRequest.ProtoReflect.Descriptor instead.
func (*UnmountAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_mount_v1_mount_proto_rawDescGZIP(), []int{5}
}

type UnmountAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnmountAllResponse) Reset() {
	*x = UnmountAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmountAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountAllResponse) ProtoMessage() {}

func (x *UnmountAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountAllResponse.ProtoReflect.Descriptor instead.
func (*UnmountAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_mount_v1_mount_proto_rawDescGZIP(), []int{6}
}

// MountInContainerRequest carries a single mount to apply inside the
// mount namespace owned by an existing container.
type MountInContainerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// container_pid is a PID, inside the VM, of any process belonging to
	// the target container; vminitd reads /proc/<pid>/ns/mnt to find the
	// mount namespace.
	ContainerPid uint32     `protobuf:"varint,1,opt,name=container_pid,json=containerPid,proto3" json:"container_pid,omitempty"`
	Mount        *MountSpec `protobuf:"bytes,2,opt,name=mount,proto3" json:"mount,omitempty"`
}

func (x *MountInContainerRequest) Reset() {
	*x = MountInContainerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MountInContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountInContainerRequest) ProtoMessage() {}

func (x *MountInContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountInContainerRequest.ProtoReflect.Descriptor instead.
func (*MountInContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_mount_v1_mount_proto_rawDescGZIP(), []int{7}
}

func (x *MountInContainerRequest) GetContainerPid() uint32 {
	if x != nil {
		return x.ContainerPid
	}
	return 0
}

func (x *MountInContainerRequest) GetMount() *MountSpec {
	if x != nil {
		return x.Mount
	}
	return nil
}

type MountInContainerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MountInContainerResponse) Reset() {
	*x = MountInContainerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MountInContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountInContainerResponse) ProtoMessage() {}

func (x *MountInContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountInContainerResponse.ProtoReflect.Descriptor instead.
func (*MountInContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_mount_v1_mount_proto_rawDescGZIP(), []int{8}
}

// UnmountInContainerRequest names a single in-container target to umount.
type UnmountInContainerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerPid uint32 `protobuf:"varint,1,opt,name=container_pid,json=containerPid,proto3" json:"container_pid,omitempty"`
	Target       string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *UnmountInContainerRequest) Reset() {
	*x = UnmountInContainerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmountInContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountInContainerRequest) ProtoMessage() {}

func (x *UnmountInContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountInContainerRequest.ProtoReflect.Descriptor instead.
func (*UnmountInContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_mount_v1_mount_proto_rawDescGZIP(), []int{9}
}

func (x *UnmountInContainerRequest) GetContainerPid() uint32 {
	if x != nil {
		return x.ContainerPid
	}
	return 0
}

func (x *UnmountInContainerRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type UnmountInContainerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnmountInContainerResponse) Reset() {
	*x = UnmountInContainerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnmountInContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmountInContainerResponse) ProtoMessage() {}

func (x *UnmountInContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmountInContainerResponse.ProtoReflect.Descriptor instead.
func (*UnmountInContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_mount_v1_mount_proto_rawDescGZIP(), []int{10}
}

var File_proto_nerdbox_services_mount_v1_mount_proto protoreflect.FileDescriptor

var file_proto_nerdbox_services_mount_v1_mount_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x72, 0x64, 0x62, 0x6f, 0x78, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x24, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74,
	0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x76, 0x31, 0x22, 0x69, 0x0a, 0x09, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x70, 0x65, 0x63,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x5a,
	0x0a, 0x0f, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x47, 0x0a, 0x06, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76,
	0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x70,
	0x65, 0x63, 0x52, 0x06, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x22, 0x12, 0x0a, 0x10, 0x4d, 0x6f,
	0x75, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x28,
	0x0a, 0x0e, 0x55, 0x6e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x55, 0x6e, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x55,
	0x6e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x14, 0x0a, 0x12, 0x55, 0x6e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x17, 0x4d, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f,
	0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x50, 0x69, 0x64, 0x12, 0x45, 0x0a, 0x05, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f,
	0x75, 0x6e, 0x74, 0x53, 0x70, 0x65, 0x63, 0x52, 0x05, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x1a,
	0x0a, 0x18, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x58, 0x0a, 0x19, 0x55, 0x6e,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x5f, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x50, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x55, 0x6e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0xa9, 0x05, 0x0a, 0x05, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x79, 0x0a, 0x08,
	0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x35, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x36, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69,
	0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x76, 0x0a, 0x07, 0x55, 0x6e, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x34, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e,
	0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x6e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x7f, 0x0a, 0x0a, 0x55, 0x6e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x37, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69,
	0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x38, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x91, 0x01, 0x0a, 0x10, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x3d, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x3e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x97, 0x01, 0x0a, 0x12, 0x55, 0x6e, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x3f, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x6e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x40, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74,
	0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3b,
	0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2f, 0x6e, 0x65, 0x72, 0x64, 0x62, 0x6f, 0x78, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_nerdbox_services_mount_v1_mount_proto_rawDescOnce sync.Once
	file_proto_nerdbox_services_mount_v1_mount_proto_rawDescData = file_proto_nerdbox_services_mount_v1_mount_proto_rawDesc
)

func file_proto_nerdbox_services_mount_v1_mount_proto_rawDescGZIP() []byte {
	file_proto_nerdbox_services_mount_v1_mount_proto_rawDescOnce.Do(func() {
		file_proto_nerdbox_services_mount_v1_mount_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_nerdbox_services_mount_v1_mount_proto_rawDescData)
	})
	return file_proto_nerdbox_services_mount_v1_mount_proto_rawDescData
}

var file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_nerdbox_services_mount_v1_mount_proto_goTypes = []interface{}{
	(*MountSpec)(nil),                  // 0: containerd.vminitd.services.mount.v1.MountSpec
	(*MountAllRequest)(nil),            // 1: containerd.vminitd.services.mount.v1.MountAllRequest
	(*MountAllResponse)(nil),           // 2: containerd.vminitd.services.mount.v1.MountAllResponse
	(*UnmountRequest)(nil),             // 3: containerd.vminitd.services.mount.v1.UnmountRequest
	(*UnmountResponse)(nil),            // 4: containerd.vminitd.services.mount.v1.UnmountResponse
	(*UnmountAllRequest)(nil),          // 5: containerd.vminitd.services.mount.v1.UnmountAllRequest
	(*UnmountAllResponse)(nil),         // 6: containerd.vminitd.services.mount.v1.UnmountAllResponse
	(*MountInContainerRequest)(nil),    // 7: containerd.vminitd.services.mount.v1.MountInContainerRequest
	(*MountInContainerResponse)(nil),   // 8: containerd.vminitd.services.mount.v1.MountInContainerResponse
	(*UnmountInContainerRequest)(nil),  // 9: containerd.vminitd.services.mount.v1.UnmountInContainerRequest
	(*UnmountInContainerResponse)(nil), // 10: containerd.vminitd.services.mount.v1.UnmountInContainerResponse
}
var file_proto_nerdbox_services_mount_v1_mount_proto_depIdxs = []int32{
	0,  // 0: containerd.vminitd.services.mount.v1.MountAllRequest.mounts:type_name -> containerd.vminitd.services.mount.v1.MountSpec
	0,  // 1: containerd.vminitd.services.mount.v1.MountInContainerRequest.mount:type_name -> containerd.vminitd.services.mount.v1.MountSpec
	1,  // 2: containerd.vminitd.services.mount.v1.Mount.MountAll:input_type -> containerd.vminitd.services.mount.v1.MountAllRequest
	3,  // 3: containerd.vminitd.services.mount.v1.Mount.Unmount:input_type -> containerd.vminitd.services.mount.v1.UnmountRequest
	5,  // 4: containerd.vminitd.services.mount.v1.Mount.UnmountAll:input_type -> containerd.vminitd.services.mount.v1.UnmountAllRequest
	7,  // 5: containerd.vminitd.services.mount.v1.Mount.MountInContainer:input_type -> containerd.vminitd.services.mount.v1.MountInContainerRequest
	9,  // 6: containerd.vminitd.services.mount.v1.Mount.UnmountInContainer:input_type -> containerd.vminitd.services.mount.v1.UnmountInContainerRequest
	2,  // 7: containerd.vminitd.services.mount.v1.Mount.MountAll:output_type -> containerd.vminitd.services.mount.v1.MountAllResponse
	4,  // 8: containerd.vminitd.services.mount.v1.Mount.Unmount:output_type -> containerd.vminitd.services.mount.v1.UnmountResponse
	6,  // 9: containerd.vminitd.services.mount.v1.Mount.UnmountAll:output_type -> containerd.vminitd.services.mount.v1.UnmountAllResponse
	8,  // 10: containerd.vminitd.services.mount.v1.Mount.MountInContainer:output_type -> containerd.vminitd.services.mount.v1.MountInContainerResponse
	10, // 11: containerd.vminitd.services.mount.v1.Mount.UnmountInContainer:output_type -> containerd.vminitd.services.mount.v1.UnmountInContainerResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_nerdbox_services_mount_v1_mount_proto_init() }
func file_proto_nerdbox_services_mount_v1_mount_proto_init() {
	if File_proto_nerdbox_services_mount_v1_mount_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MountSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MountAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MountAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnmountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnmountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnmountAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnmountAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MountInContainerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MountInContainerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnmountInContainerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnmountInContainerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_nerdbox_services_mount_v1_mount_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_nerdbox_services_mount_v1_mount_proto_goTypes,
		DependencyIndexes: file_proto_nerdbox_services_mount_v1_mount_proto_depIdxs,
		MessageInfos:      file_proto_nerdbox_services_mount_v1_mount_proto_msgTypes,
	}.Build()
	File_proto_nerdbox_services_mount_v1_mount_proto = out.File
	file_proto_nerdbox_services_mount_v1_mount_proto_rawDesc = nil
	file_proto_nerdbox_services_mount_v1_mount_proto_goTypes = nil
	file_proto_nerdbox_services_mount_v1_mount_proto_depIdxs = nil
}
