//
//Copyright The containerd Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: proto/nerdbox/services/sharedresources/v1/sharedresources.proto

package sharedresources

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type identifies a kind of guest-side shared resource: created once per
// (group id, type) and addressed by a guest path thereafter. Most values are
// Linux namespace types; TYPE_DEVSHM is not — see its own comment.
type Type int32

const (
	Type_TYPE_UNSPECIFIED       Type = 0
	Type_TYPE_NAMESPACE_IPC     Type = 1
	Type_TYPE_NAMESPACE_PID     Type = 2
	Type_TYPE_NAMESPACE_NETWORK Type = 3
	// TYPE_DEVSHM is not an OCI namespace: it is a per-group tmpfs,
	// mounted once and reused, that sharing containers bind-mount their
	// /dev/shm onto so writes through it are real shared memory (guest
	// RAM), not just a shared IPC namespace identifier. It reuses this
	// same create-once/reuse/path-return mechanism because the shape of
	// the problem — and the "only pay for it if actually requested"
	// requirement — is identical to the namespace types.
	Type_TYPE_DEVSHM Type = 4
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_NAMESPACE_IPC",
		2: "TYPE_NAMESPACE_PID",
		3: "TYPE_NAMESPACE_NETWORK",
		4: "TYPE_DEVSHM",
	}
	Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":       0,
		"TYPE_NAMESPACE_IPC":     1,
		"TYPE_NAMESPACE_PID":     2,
		"TYPE_NAMESPACE_NETWORK": 3,
		"TYPE_DEVSHM":            4,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDescGZIP(), []int{0}
}

// SharedResource is a created resource and the guest path it is pinned at.
type SharedResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=containerd.vminitd.services.sharedresources.v1.Type" json:"type,omitempty"`
	// path is a guest-side path. For a namespace type, it is a bind-mount
	// path suitable for use directly as an OCI runtime spec
	// LinuxNamespace.Path. For TYPE_DEVSHM, it is a directory suitable for
	// use as an OCI runtime spec Mount.Source with Type "bind".
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *SharedResource) Reset() {
	*x = SharedResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SharedResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedResource) ProtoMessage() {}

func (x *SharedResource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedResource.ProtoReflect.Descriptor instead.
func (*SharedResource) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDescGZIP(), []int{0}
}

func (x *SharedResource) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (x *SharedResource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id groups the resources being created. Resources are created once
	// per (id, type) and reused, so repeating a request returns the paths
	// of the resources already created rather than creating new ones.
	ID string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// types are the resource types to create. Types already created for
	// id are returned without being recreated.
	Types []Type `protobuf:"varint,2,rep,packed,name=types,proto3,enum=containerd.vminitd.services.sharedresources.v1.Type" json:"types,omitempty"`
	// dev_shm_size_bytes is the tmpfs size to use when creating a
	// TYPE_DEVSHM resource for id for the first time. Ignored for every
	// other type, and ignored if a TYPE_DEVSHM resource for id already
	// exists (the size used by whichever caller created it first wins;
	// callers within one sandbox are expected to agree on it, since
	// containerd sends every member container of a pod the same /dev/shm
	// size). A value that is zero or absent falls back to a guest-side
	// default.
	DevShmSizeBytes int64 `protobuf:"varint,3,opt,name=dev_shm_size_bytes,json=devShmSizeBytes,proto3" json:"dev_shm_size_bytes,omitempty"`
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateRequest) GetTypes() []Type {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *CreateRequest) GetDevShmSizeBytes() int64 {
	if x != nil {
		return x.DevShmSizeBytes
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// resources contains one entry per requested type.
	Resources []*SharedResource `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetResources() []*SharedResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is the group to delete resources from.
	ID string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// types are the resource types to delete. An empty list deletes every
	// resource belonging to id.
	//
	// Deleting a namespace that containers are still using is a caller
	// error: for a PID namespace it kills the anchor process, which makes
	// the kernel tear the namespace down and kill everything in it.
	Types []Type `protobuf:"varint,2,rep,packed,name=types,proto3,enum=containerd.vminitd.services.sharedresources.v1.Type" json:"types,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *DeleteRequest) GetTypes() []Type {
	if x != nil {
		return x.Types
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDescGZIP(), []int{4}
}

var File_proto_nerdbox_services_sharedresources_v1_sharedresources_proto protoreflect.FileDescriptor

var file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDesc = []byte{
	0x0a, 0x3f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x72, 0x64, 0x62, 0x6f, 0x78, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d,
	0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x22, 0x6e, 0x0a, 0x0e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x34, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76,
	0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x22, 0x98, 0x01, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x4a, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0e, 0x32, 0x34, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e,
	0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12,
	0x2b, 0x0a, 0x12, 0x64, 0x65, 0x76, 0x5f, 0x73, 0x68, 0x6d, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x64, 0x65, 0x76,
	0x53, 0x68, 0x6d, 0x53, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x6e, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c,
	0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x3e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76,
	0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x6b, 0x0a, 0x0d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x4a, 0x0a,
	0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x34, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74,
	0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x79, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x53, 0x50, 0x41, 0x43, 0x45, 0x5f, 0x49, 0x50, 0x43, 0x10,
	0x01, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x53, 0x50,
	0x41, 0x43, 0x45, 0x5f, 0x50, 0x49, 0x44, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x53, 0x50, 0x41, 0x43, 0x45, 0x5f, 0x4e, 0x45, 0x54, 0x57,
	0x4f, 0x52, 0x4b, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45,
	0x56, 0x53, 0x48, 0x4d, 0x10, 0x04, 0x32, 0xa5, 0x02, 0x0a, 0x0f, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x87, 0x01, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x3d, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x3e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x87, 0x01, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x3d, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69,
	0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3e,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e,
	0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4f,
	0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2f, 0x6e, 0x65, 0x72, 0x64, 0x62, 0x6f, 0x78, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x3b,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDescOnce sync.Once
	file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDescData = file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDesc
)

func file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDescGZIP() []byte {
	file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDescOnce.Do(func() {
		file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDescData)
	})
	return file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDescData
}

var file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_goTypes = []interface{}{
	(Type)(0),              // 0: containerd.vminitd.services.sharedresources.v1.Type
	(*SharedResource)(nil), // 1: containerd.vminitd.services.sharedresources.v1.SharedResource
	(*CreateRequest)(nil),  // 2: containerd.vminitd.services.sharedresources.v1.CreateRequest
	(*CreateResponse)(nil), // 3: containerd.vminitd.services.sharedresources.v1.CreateResponse
	(*DeleteRequest)(nil),  // 4: containerd.vminitd.services.sharedresources.v1.DeleteRequest
	(*DeleteResponse)(nil), // 5: containerd.vminitd.services.sharedresources.v1.DeleteResponse
}
var file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_depIdxs = []int32{
	0, // 0: containerd.vminitd.services.sharedresources.v1.SharedResource.type:type_name -> containerd.vminitd.services.sharedresources.v1.Type
	0, // 1: containerd.vminitd.services.sharedresources.v1.CreateRequest.types:type_name -> containerd.vminitd.services.sharedresources.v1.Type
	1, // 2: containerd.vminitd.services.sharedresources.v1.CreateResponse.resources:type_name -> containerd.vminitd.services.sharedresources.v1.SharedResource
	0, // 3: containerd.vminitd.services.sharedresources.v1.DeleteRequest.types:type_name -> containerd.vminitd.services.sharedresources.v1.Type
	2, // 4: containerd.vminitd.services.sharedresources.v1.SharedResources.Create:input_type -> containerd.vminitd.services.sharedresources.v1.CreateRequest
	4, // 5: containerd.vminitd.services.sharedresources.v1.SharedResources.Delete:input_type -> containerd.vminitd.services.sharedresources.v1.DeleteRequest
	3, // 6: containerd.vminitd.services.sharedresources.v1.SharedResources.Create:output_type -> containerd.vminitd.services.sharedresources.v1.CreateResponse
	5, // 7: containerd.vminitd.services.sharedresources.v1.SharedResources.Delete:output_type -> containerd.vminitd.services.sharedresources.v1.DeleteResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_init() }
func file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_init() {
	if File_proto_nerdbox_services_sharedresources_v1_sharedresources_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SharedResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_goTypes,
		DependencyIndexes: file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_depIdxs,
		EnumInfos:         file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_enumTypes,
		MessageInfos:      file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_msgTypes,
	}.Build()
	File_proto_nerdbox_services_sharedresources_v1_sharedresources_proto = out.File
	file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_rawDesc = nil
	file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_goTypes = nil
	file_proto_nerdbox_services_sharedresources_v1_sharedresources_proto_depIdxs = nil
}
