// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: proto/nerdbox/services/sharedresources/v1/sharedresources.proto
package sharedresources

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type TTRPCSharedResourcesService interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterTTRPCSharedResourcesService(srv *ttrpc.Server, svc TTRPCSharedResourcesService) {
	srv.RegisterService("containerd.vminitd.services.sharedresources.v1.SharedResources", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"Create": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req CreateRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Create(ctx, &req)
			},
			"Delete": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req DeleteRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Delete(ctx, &req)
			},
		},
	})
}

type ttrpcsharedresourcesClient struct {
	client *ttrpc.Client
}

func NewTTRPCSharedResourcesClient(client *ttrpc.Client) TTRPCSharedResourcesService {
	return &ttrpcsharedresourcesClient{
		client: client,
	}
}

func (c *ttrpcsharedresourcesClient) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	var resp CreateResponse
	if err := c.client.Call(ctx, "containerd.vminitd.services.sharedresources.v1.SharedResources", "Create", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcsharedresourcesClient) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	var resp DeleteResponse
	if err := c.client.Call(ctx, "containerd.vminitd.services.sharedresources.v1.SharedResources", "Delete", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
