// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: proto/nerdbox/services/socketforward/v1/socketforward.proto
package socketforward

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type TTRPCSocketForwardService interface {
	Bind(context.Context, *BindRequest) (*emptypb.Empty, error)
	Accept(context.Context, TTRPCSocketForward_AcceptServer) error
}

type TTRPCSocketForward_AcceptServer interface {
	Send(*ConnectRequest) error
	Recv() (*ConnectResult, error)
	ttrpc.StreamServer
}

type ttrpcsocketforwardAcceptServer struct {
	ttrpc.StreamServer
}

func (x *ttrpcsocketforwardAcceptServer) Send(m *ConnectRequest) error {
	return x.StreamServer.SendMsg(m)
}

func (x *ttrpcsocketforwardAcceptServer) Recv() (*ConnectResult, error) {
	m := new(ConnectResult)
	if err := x.StreamServer.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func RegisterTTRPCSocketForwardService(srv *ttrpc.Server, svc TTRPCSocketForwardService) {
	srv.RegisterService("nerdbox.services.socketforward.v1.SocketForward", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"Bind": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req BindRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Bind(ctx, &req)
			},
		},
		Streams: map[string]ttrpc.Stream{
			"Accept": {
				Handler: func(ctx context.Context, stream ttrpc.StreamServer) (interface{}, error) {
					return nil, svc.Accept(ctx, &ttrpcsocketforwardAcceptServer{stream})
				},
				StreamingClient: true,
				StreamingServer: true,
			},
		},
	})
}

type TTRPCSocketForwardClient interface {
	Bind(context.Context, *BindRequest) (*emptypb.Empty, error)
	Accept(context.Context) (TTRPCSocketForward_AcceptClient, error)
}

type ttrpcsocketforwardClient struct {
	client *ttrpc.Client
}

func NewTTRPCSocketForwardClient(client *ttrpc.Client) TTRPCSocketForwardClient {
	return &ttrpcsocketforwardClient{
		client: client,
	}
}

func (c *ttrpcsocketforwardClient) Bind(ctx context.Context, req *BindRequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	if err := c.client.Call(ctx, "nerdbox.services.socketforward.v1.SocketForward", "Bind", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcsocketforwardClient) Accept(ctx context.Context) (TTRPCSocketForward_AcceptClient, error) {
	stream, err := c.client.NewStream(ctx, &ttrpc.StreamDesc{
		StreamingClient: true,
		StreamingServer: true,
	}, "nerdbox.services.socketforward.v1.SocketForward", "Accept", nil)
	if err != nil {
		return nil, err
	}
	x := &ttrpcsocketforwardAcceptClient{stream}
	return x, nil
}

type TTRPCSocketForward_AcceptClient interface {
	Send(*ConnectResult) error
	Recv() (*ConnectRequest, error)
	ttrpc.ClientStream
}

type ttrpcsocketforwardAcceptClient struct {
	ttrpc.ClientStream
}

func (x *ttrpcsocketforwardAcceptClient) Send(m *ConnectResult) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ttrpcsocketforwardAcceptClient) Recv() (*ConnectRequest, error) {
	m := new(ConnectRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}
