//go:build linux

/*
   Copyright The containerd Authors.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package transfer

import (
	"os"
	"path/filepath"

	"golang.org/x/sys/unix"
)

// Filesystems whose contents are generated by the kernel rather than
// stored. Copying them is not meaningful: their files report a size that
// does not match what a read returns, so archiving one fails partway
// through with a size mismatch rather than producing anything usable, and
// extracting onto one writes into kernel interfaces rather than files.
//
// Only kernel-generated filesystems are listed. tmpfs, overlay and the
// like hold ordinary files and are exactly what a container's mounts are
// made of, so they must keep working.
var pseudoFSTypes = map[uint64]string{
	unix.PROC_SUPER_MAGIC:    "proc",
	unix.SYSFS_MAGIC:         "sysfs",
	unix.DEVPTS_SUPER_MAGIC:  "devpts",
	unix.CGROUP_SUPER_MAGIC:  "cgroup",
	unix.CGROUP2_SUPER_MAGIC: "cgroup2",
	unix.DEBUGFS_MAGIC:       "debugfs",
	unix.TRACEFS_MAGIC:       "tracefs",
	unix.BPF_FS_MAGIC:        "bpf",
	unix.SECURITYFS_MAGIC:    "securityfs",
	unix.SELINUX_MAGIC:       "selinuxfs",
	unix.BINFMTFS_MAGIC:      "binfmt_misc",
	unix.PSTOREFS_MAGIC:      "pstore",
	unix.EFIVARFS_MAGIC:      "efivarfs",
	unix.NSFS_MAGIC:          "nsfs",
	unix.HUGETLBFS_MAGIC:     "hugetlbfs",
}

// pseudoFS reports the name of the kernel-generated filesystem holding
// name, or "" if name is on an ordinary filesystem.
//
// A path that cannot be stat'ed is reported as ordinary, leaving the
// caller's own operation to produce the error. Reporting the failure here
// would replace a precise error with a vaguer one.
//
// This inspects the filesystem the path resolves onto, so it does not
// detect a path that reached an ordinary filesystem by way of a pseudo
// one: /proc/<pid>/root/etc lands on the root filesystem and is reported
// as ordinary. Those magic links are described on ctrfs.Handle.Do.
func pseudoFS(name string) string {
	var st unix.Statfs_t
	if err := unix.Statfs(name, &st); err != nil {
		return ""
	}
	return pseudoFSTypes[uint64(st.Type)]
}

// pseudoFSHolder reports the kernel-generated filesystem that dir would be
// created on, or "" if that filesystem is an ordinary one.
//
// dir need not exist. Creating it places it on the filesystem holding its
// nearest existing ancestor, so that is what decides the answer: asking about
// the path itself would report every directory yet to be created as ordinary,
// and creating one under, say, a cgroup filesystem is exactly what the answer
// is wanted for.
func pseudoFSHolder(dir string) string {
	for {
		if _, err := os.Lstat(dir); err == nil {
			return pseudoFS(dir)
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}
